"use strict";
const bcrypt = require("bcrypt");
/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Users",
      [
        {
          username: "Ксения Кривда",
          email: "kseniakrivda@gmail.com",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "165773725.jpg",
          rating: 5,
          numberOfRating: 1,
          placeOfMeeting: "УралМаш",
          city: "Екатеринбург",
          isAdmin: false,
        },
        {
          username: "Денис Образцов",
          email: "MenyaSlyshno@yandex.ru",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "Denis.jpg",
          rating: 5.0,
          numberOfRating: 1,
          placeOfMeeting: "У ЦУМа",
          city: "Иваново",
          isAdmin: false,
        },
        {
          username: "Евгения Задорожная",
          email: "eu.skorobogatowa@gmail.com",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "167392948.jpg",
          rating: 5,
          numberOfRating: 1,
          placeOfMeeting: "Ботанический сад",
          city: "Астана",
          isAdmin: true,
        },
        {
          username: "Максим Кошеутов",
          email: "MaxKosh@yandex.ru",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "Maks.png",
          rating: 5.0,
          numberOfRating: 1,
          placeOfMeeting: "Статуя Свободы",
          city: "Нью-Йорк",
          isAdmin: false,
        },
        {
          username: "Григорий Табачков",
          email: "Grigoriy@yandex.ru",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "T04CH7XJNBS-U069VV9U93P-dc5fb0364285-512.jpg",
          rating: 5.0,
          numberOfRating: 1,
          placeOfMeeting: "Пишите, договоримся",
          city: "Ессентуки",
          isAdmin: false,
        },
        {
          username: "Антон Атнагулов",
          email: "Atnagulov@yandex.ru",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "Anton.png",
          rating: 5.0,
          numberOfRating: 1,
          placeOfMeeting: "Метро Ладожская",
          city: "Санкт-Петербург",
          isAdmin: false,
        },
        {
          username: "Иван Рубцов",
          email: "Rubcov@yandex.ru",
          password: await bcrypt.hash("admin123", 10),
          avatarUrl: "Ivan.jpg",
          rating: 5.0,
          numberOfRating: 1,
          placeOfMeeting: "На берегу Волги",
          city: "Самара",
          isAdmin: false,
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      "Books",
      [
        {
          ownerId: 1,
          title: "1984",
          author: "Джордж Оруэлл",
          pages: 320,
          rating: 4.8,
          numberOfRating: 1,
          pictureUrl: "1984.webp",
        },
        {
          ownerId: 1,
          title: "Автостопом по галактике",
          author: "Дуглас Адамс",
          pages: 640,
          rating: 4.6,
          numberOfRating: 1,
          pictureUrl: "Avtostopom.webp",
        },
        {
          ownerId: 1,
          title: "Бойня №5",
          author: "Курт Воннегут",
          pages: 224,
          rating: 4.2,
          numberOfRating: 1,
          pictureUrl: "Boinya.webp",
        },
        {
          ownerId: 1,
          title: "Преступление и наказание",
          author: "Фёдор Достоевский",
          pages: 672,
          rating: 3.0,
          numberOfRating: 1,
          pictureUrl: "crime.webp",
        },
        {
          ownerId: 2,
          title: "Гений",
          author: "Теодор Драйзер",
          pages: 736,
          rating: 4.0,
          numberOfRating: 1,
          pictureUrl: "Genii.webp",
        },
        {
          ownerId: 2,
          title: "Гордость и предубеждение",
          author: "Джейн Остен",
          pages: 416,
          rating: 5.0,
          numberOfRating: 1,
          pictureUrl: "Gordost.webp",
        },
        {
          ownerId: 2,
          title: "Великий Гэтсби",
          author: "Фрэнсис Скотт Фицджеральд",
          pages: 256,
          rating: 4.8,
          numberOfRating: 1,
          pictureUrl: "Great_Gatsby.webp",
        },
        {
          ownerId: 2,
          title: "О мышах и людях",
          author: "Джон Стейнбек",
          pages: 256,
          rating: 4.6,
          numberOfRating: 1,
          pictureUrl: "O_myshax.webp",
        },
        {
          ownerId: 1,
          title: "Грозовой Перевал",
          author: "Эмили Бронте",
          pages: 384,
          rating: 5.0,
          numberOfRating: 1,
          pictureUrl: "Pereval.webp",
        },
        {
          ownerId: 2,
          title: "Ромео и Джульетта",
          author: "Уильям Шекспир",
          pages: 192,
          rating: 4.5,
          numberOfRating: 1,
          pictureUrl: "Romeo.webp",
        },
        {
          ownerId: 1,
          title: "Скотный двор",
          author: "Джордж Оруэлл",
          pages: 160,
          rating: 4.2,
          numberOfRating: 1,
          pictureUrl: "Skotny_dvor.webp",
        },
        {
          ownerId: 2,
          title: "Убить пересмешника",
          author: "Харпер Ли",
          pages: 416,
          rating: 3.9,
          numberOfRating: 1,
          pictureUrl: "Ubit_peresmeshnika.webp",
        },
        {
          ownerId: 5,
          title: "Джейн Эир",
          author: "Шарлотта Бронте",
          pages: 285,
          rating: 4.8,
          numberOfRating: 1,
          pictureUrl: "738171_550.jpg",
        },
        {
          ownerId: 5,
          title: "Таинственный Остров",
          author: "Жюль Верн",
          pages: 315,
          rating: 4.2,
          numberOfRating: 1,
          pictureUrl: "699414_1000.jpg",
        },
        {
          ownerId: 6,
          title: "Ночь в Лиссабоне",
          author: "Эрих Маия Ремарк",
          pages: 285,
          rating: 4.0,
          numberOfRating: 1,
          pictureUrl: "1407050_1000.jpg",
        },
        {
          ownerId: 6,
          title: "Алхимик",
          author: "Пауло Коэльо",
          pages: 160,
          rating: 4.1,
          numberOfRating: 1,
          pictureUrl: "488010_1000.jpg",
        },
        {
          ownerId: 6,
          title: "Chakra UI для чайников",
          author: "Антон Атнагулов",
          pages: 3120,
          rating: 5,
          numberOfRating: 1,
          pictureUrl: "1591595_1000.jpg",
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      "Reviews",
      [
        {
          userId: 1,
          bookId: 2,
          content: "Очень хорошая книга, читала прошлым летом",
          likes: 5,
          dislikes: 0,
        },
        {
          userId: 4,
          bookId: 4,
          content:
            "В этой книге бабку убивают, это ужасно, я сам чуть не умер, пока читал!",
          likes: 1,
          dislikes: 3,
        },
        {
          userId: 2,
          bookId: 8,
          content: "Крутая книга, очень интересный сюжет",
          likes: 10,
          dislikes: 2,
        },
        {
          userId: 2,
          bookId: 4,
          content: "Ой-ой-ой-ой-ой-ой, книга написана не по документации!",
          likes: 0,
          dislikes: 8,
        },
        {
          userId: 5,
          bookId: 10,
          content: "Хотел бы и я такой сказочной любви...",
          likes: 0,
          dislikes: 0,
        },
        {
          userId: 6,
          bookId: 1,
          content: "Книга пророческая",
          likes: 0,
          dislikes: 0,
        },
        {
          userId: 6,
          bookId: 3,
          content: "Ну такое, пойдет",
          likes: 0,
          dislikes: 0,
        },
        {
          userId: 5,
          bookId: 6,
          content: "Я прочитал все романы Джейн Остен. Но «Гордость и предубеждение» мой самый любимый среди них. Читается на одном дыханий. Советую читать",
          likes: 3,
          dislikes: 0,
        },
        {
          userId: 6,
          bookId: 6,
          content: "Согласен полностью с Григорием, книга очень романтичная и читается на одном дыхании ❤️",
          likes: 13,
          dislikes: 1,
        },
        {
          userId: 7,
          bookId: 11,
          content: "Привет всем!) Помогаю сегодня до 17:30",
          likes: 0,
          dislikes: 2,
        },
        {
          userId: 7,
          bookId: 11,
          content: "Чат перепутал, извините",
          likes: 0,
          dislikes: 0,
        },
      ],
      {}
    );

    await queryInterface.bulkInsert(
      "Exchanges",
      [
        {
          fromUser: 1,
          fromBook: 3,
          toUser: 2,
          toBook: 5,
          status: "Ожидает подтверждения",
        },
        {
          fromUser: 2,
          fromBook: 8,
          toUser: 1,
          toBook: 2,
          status: "В процессе",
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Exchanges", null, {});
    await queryInterface.bulkDelete("Reviews", null, {});
    await queryInterface.bulkDelete("Books", null, {});
    await queryInterface.bulkDelete("Users", null, {});
  },
};
